### ISSUE TITLE
Does not work for writers configuration(s)?

### ISSUE THREAD

**Issue by KenjiTakahashi** [pmwmedia/tinylog-typesafe-config-example#1]
Consider config like this (simplified for brevity):
```
tinylog.format = {date} [{{thread}|min-size=30}] {{level}|min-size=8} {class}.{method}:{line} - {message}

tinylog.writer1 = rollingfile
tinylog.writer1.filename = info.log
```

The code from this repo produces the following mapping:
```
{
tinylog.writer1.filename=info.log,
tinylog.format={date} [{{thread}|min-size=30}] {{level}|min-size=8} {class}.{method}:{line} - {message}
}
```

See that the `tinylog.writer1 = rollingfile` part is missing. My guess is that it interprets the config like equivalent to
```
tinylog.writer1 = rollingfile
tinylog.writer1 = {filename = info.log}
```
so the specific option(s) overwrite the "top level" one.

Any ideas on how to make it to work?

**Comment by pmwmedia** [comment]
Since type-safe configuration does not support a value for top-level entries if there are child entries, it is indeed difficult to define the writers. I think that the easiest way to solve this is to introduce a fake child key for the writer type:

```
tinylog {
	format = "{date} [{{thread}|min-size=30}] {{level}|min-size=8} {class}.{method}:{line} - {message}"
	writer {
		type = rollingfile
		filename = info.log
		backups = 42
	}
}
```
Then you can map the fake key to the actual key when loading the configuration:

```java
public class Application {
	
	private static final Pattern PATTERN = Pattern.compile("(tinylog\\.writer\\w*)(\\.type)");

	public static void main(final String[] args) {
		Config config = ConfigFactory.load("tinylog.conf").resolve().withOnlyPath("tinylog");
		Function<String, String> keyMapper = key -> { Matcher matcher = PATTERN.matcher(key); return matcher.matches() ? matcher.group(1) : key; };
		Stream<Entry<String, ConfigValue>> stream = config.entrySet().stream();
		Map<String, ?> map = stream.collect(Collectors.toMap(entry -> keyMapper.apply(entry.getKey()), entry -> entry.getValue().unwrapped()));
		
		Configurator.fromMap(map).activate();
		
		Logger.info("Hello World!");
	}

}
```

**Comment by KenjiTakahashi** [comment]
Yeah, it seems to work. Not the prettiest solution in the world, but does the trick, thanks.
Maybe it will be worth to add a note about it somewhere in the repo, for others who might stumble upon this?

**Comment by pmwmedia** [comment]
Yes, I agree it is not the prettiest solution. Better ideas are welcome :-)

I have updated the example in this repository.
